<?xml version="1.0" encoding="utf-8"?><Database Name="DookkiWebApp" Class="DookkiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-HBID7S9\SQLEXPRESS;Initial Catalog=DookkiWebApp;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DookkiWebApp" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiNhanh" Member="ChiNhanhs">
    <Type Name="ChiNhanh">
      <Column Name="MaCN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCN" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Hotline" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ThongTin" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaTP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChiNhanh_DatBan" Member="DatBans" ThisKey="MaCN" OtherKey="MaCN" Type="DatBan" />
      <Association Name="ThanhPho_ChiNhanh" Member="ThanhPho" ThisKey="MaTP" OtherKey="MaTP" Type="ThanhPho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatBan" Member="DatBans">
    <Type Name="DatBan">
      <Column Name="MaDatBan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaQR" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChiNhanh_DatBan" Member="ChiNhanh" ThisKey="MaCN" OtherKey="MaCN" Type="ChiNhanh" IsForeignKey="true" />
      <Association Name="KhachHang_DatBan" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KH_Voucher" Member="KH_Vouchers">
    <Type Name="KH_Voucher">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaVoucher" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaQR" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiHan" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_KH_Voucher" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="Voucher_KH_Voucher" Member="Voucher" ThisKey="MaVoucher" OtherKey="MaVoucher" Type="Voucher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DienThoaiKH" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Diem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TongChiTieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_DatBan" Member="DatBans" ThisKey="MaKH" OtherKey="MaKH" Type="DatBan" />
      <Association Name="KhachHang_KH_Voucher" Member="KH_Vouchers" ThisKey="MaKH" OtherKey="MaKH" Type="KH_Voucher" />
      <Association Name="KhachHang_TichDiem" Member="TichDiems" ThisKey="MaKH" OtherKey="MaKH" Type="TichDiem" />
      <Association Name="KhachHang_ThongBao" Member="ThongBaos" ThisKey="MaKH" OtherKey="MaKH" Type="ThongBao" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhPho" Member="ThanhPhos">
    <Type Name="ThanhPho">
      <Column Name="MaTP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTP" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Association Name="ThanhPho_ChiNhanh" Member="ChiNhanhs" ThisKey="MaTP" OtherKey="MaTP" Type="ChiNhanh" />
    </Type>
  </Table>
  <Table Name="dbo.TichDiem" Member="TichDiems">
    <Type Name="TichDiem">
      <Column Name="MaTichDiem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChiTiet" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhachHang_TichDiem" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongBao" Member="ThongBaos">
    <Type Name="ThongBao">
      <Column Name="MaTB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="ChiTiet" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhachHang_ThongBao" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Voucher" Member="Vouchers">
    <Type Name="Voucher">
      <Column Name="MaVoucher" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChiTiet" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhanTram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiamToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Diem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DieuKien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Voucher_KH_Voucher" Member="KH_Vouchers" ThisKey="MaVoucher" OtherKey="MaVoucher" Type="KH_Voucher" />
    </Type>
  </Table>
</Database>